# Objective of analyzing Spotify dataset in Jupyter:

- Confirm datatypes of all columns and convert to compatible datatypes for analysis. 
- For example, convert objects to string and date columns to datetime
- Check for Null values and replace nulls with default values. For this analysis, I am changing default values for null artists and congs to Missing and missing dates to alpha date i.e. '1900-01-01'
- Find number of unique songs by spotify_id in the dataset
- After analyzing the dataset I found that the unique identifier for this dataset is Spotify_id, name, artist, country and snapshot_date
- Describe the dataset tyo find statistics about the columns like min, max, count, std deviation to get the distribution of values in the columns
- Split the artist column to have unique row for each artist rather than a list of comma separated values in a single column

In [181]:
# import packages
import pandas as pd
from datetime import timedelta

In [182]:
# Read csv as pandas dataframe

df_raw_data = pd.read_csv("https://storage.googleapis.com/kaggle-spotify-bucket/universal_top_spotify_songs.csv")

# display top 5 rows

df_raw_data.head()

,spotify_id,name,artists,daily_rank,daily_movement,weekly_movement,country,snapshot_date,popularity,is_explicit,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,2HafqoJbgXdtjwCOvNEF14,Si No Estás,iñigo quintero,1,0,3,NaN,2023-10-27,97,False,...,5,-8.720,1,0.0285,0.8270,0.000000,0.1380,0.524,98.224,4
1,7x9aauaA9cu6tyfpHnqDLo,Seven (feat. Latto) (Explicit Ver.),"Jung Kook, Latto",2,4,0,NaN,2023-10-27,97,True,...,11,-4.107,1,0.0434,0.3110,0.000000,0.0815,0.890,124.997,4
2,3rUGC1vUpkDG9CZFHMur1t,greedy,Tate McRae,3,-1,2,NaN,2023-10-27,99,True,...,6,-3.180,0,0.0319,0.2560,0.000000,0.1140,0.844,111.018,1
3,4MjDJD8cW7iVeWInc2Bdyj,MONACO,Bad Bunny,4,-1,-3,NaN,2023-10-27,96,True,...,4,-5.009,0,0.0680,0.1500,0.000402,0.5800,0.130,139.056,4
4,7iQXYTyuG13aoeHxGG28Nh,PERRO NEGRO,"Bad Bunny, Feid",5,0,1,NaN,2023-10-27,94,True,...,5,-2.248,1,0.2620,0.0887,0.000022,0.1790,0.345,96.057,4

In [183]:
# Get datatypes of all columns
df_raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36400 entries, 0 to 36399
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   spotify_id          36400 non-null  object
 1   name                36399 non-null  object
 2   artists             36399 non-null  object
 3   daily_rank          36400 non-null  int64
 4   daily_movement      36400 non-null  int64
 5   weekly_movement     36400 non-null  int64
 6   country             35900 non-null  object
 7   snapshot_date       36400 non-null  object
 8   popularity          36400 non-null  int64
 9   is_explicit         36400 non-null  bool
 10  duration_ms         36400 non-null  int64
 11  album_name          36399 non-null  object
 12  album_release_date  36399 non-null  object
 13  danceability        36400 non-null  float64
 14  energy              36400 non-null  float64
 15  key                 36400 non-null  int64
 16  loudness            36400 non-null  float64
 17  mode                36400 non-null  int64
 18  speechiness         36400 non-null  float64
 19  acousticness        36400 non-null  float64
 20  instrumentalness    36400 non-null  float64
 21  liveness            36400 non-null  float64
 22  valence             36400 non-null  float64
 23  tempo               36400 non-null  float64
 24  time_signature      36400 non-null  int64
dtypes: bool(1), float64(9), int64(8), object(7)
memory usage: 6.7+ MB

In [184]:
# create a copy of raw data

df_updated = df_raw_data.copy()
df_updated.head()

,spotify_id,name,artists,daily_rank,daily_movement,weekly_movement,country,snapshot_date,popularity,is_explicit,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,2HafqoJbgXdtjwCOvNEF14,Si No Estás,iñigo quintero,1,0,3,NaN,2023-10-27,97,False,...,5,-8.720,1,0.0285,0.8270,0.000000,0.1380,0.524,98.224,4
1,7x9aauaA9cu6tyfpHnqDLo,Seven (feat. Latto) (Explicit Ver.),"Jung Kook, Latto",2,4,0,NaN,2023-10-27,97,True,...,11,-4.107,1,0.0434,0.3110,0.000000,0.0815,0.890,124.997,4
2,3rUGC1vUpkDG9CZFHMur1t,greedy,Tate McRae,3,-1,2,NaN,2023-10-27,99,True,...,6,-3.180,0,0.0319,0.2560,0.000000,0.1140,0.844,111.018,1
3,4MjDJD8cW7iVeWInc2Bdyj,MONACO,Bad Bunny,4,-1,-3,NaN,2023-10-27,96,True,...,4,-5.009,0,0.0680,0.1500,0.000402,0.5800,0.130,139.056,4
4,7iQXYTyuG13aoeHxGG28Nh,PERRO NEGRO,"Bad Bunny, Feid",5,0,1,NaN,2023-10-27,94,True,...,5,-2.248,1,0.2620,0.0887,0.000022,0.1790,0.345,96.057,4

In [185]:
# convert dates columns to date format

df_updated[['album_release_date', 'snapshot_date']] = df_updated[['album_release_date', 'snapshot_date']].apply(pd.to_datetime)
df_updated[['name', 'artists', 'country', 'album_name']] = df_updated[['name', 'artists', 'country', 'album_name']].astype('string')

# confirm if columns are updated to new datatypes
df_updated.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36400 entries, 0 to 36399
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   spotify_id          36400 non-null  object
 1   name                36399 non-null  string
 2   artists             36399 non-null  string
 3   daily_rank          36400 non-null  int64
 4   daily_movement      36400 non-null  int64
 5   weekly_movement     36400 non-null  int64
 6   country             35900 non-null  string
 7   snapshot_date       36400 non-null  datetime64[ns]
 8   popularity          36400 non-null  int64
 9   is_explicit         36400 non-null  bool
 10  duration_ms         36400 non-null  int64
 11  album_name          36399 non-null  string
 12  album_release_date  36399 non-null  datetime64[ns]
 13  danceability        36400 non-null  float64
 14  energy              36400 non-null  float64
 15  key                 36400 non-null  int64
 16  loudness            36400 non-null  float64
 17  mode                36400 non-null  int64
 18  speechiness         36400 non-null  float64
 19  acousticness        36400 non-null  float64
 20  instrumentalness    36400 non-null  float64
 21  liveness            36400 non-null  float64
 22  valence             36400 non-null  float64
 23  tempo               36400 non-null  float64
 24  time_signature      36400 non-null  int64
dtypes: bool(1), datetime64[ns](2), float64(9), int64(8), object(1), string(4)
memory usage: 6.7+ MB

In [186]:
# find total NaN values in each column
df_updated.isna().sum()

spotify_id              0
name                    1
artists                 1
daily_rank              0
daily_movement          0
weekly_movement         0
country               500
snapshot_date           0
popularity              0
is_explicit             0
duration_ms             0
album_name              1
album_release_date      1
danceability            0
energy                  0
key                     0
loudness                0
mode                    0
speechiness             0
acousticness            0
instrumentalness        0
liveness                0
valence                 0
tempo                   0
time_signature          0
dtype: int64

In [187]:
# Replace null values in each column that has null values with appropriate default value
df_updated.fillna({"name": "Missing", "artists": "Missing", "country":"Global", "album_name":"Missing", "album_release_date": "1900-01-01"}, inplace=True)
df_updated.isna().sum()

/var/folders/6b/dxptz9d5049b89vmzgmtsbbh0000gn/T/ipykernel_49178/3543575028.py:2: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_updated.fillna({"name": "Missing", "artists": "Missing", "country":"Global", "album_name":"Missing", "album_release_date": "1900-01-01"}, inplace=True)

spotify_id            0
name                  0
artists               0
daily_rank            0
daily_movement        0
weekly_movement       0
country               0
snapshot_date         0
popularity            0
is_explicit           0
duration_ms           0
album_name            0
album_release_date    0
danceability          0
energy                0
key                   0
loudness              0
mode                  0
speechiness           0
acousticness          0
instrumentalness      0
liveness              0
valence               0
tempo                 0
time_signature        0
dtype: int64

In [188]:
# Add album release year as a new column
df_updated["album_release_year"] = df_updated["album_release_date"].dt.year

df_updated.head()

,spotify_id,name,artists,daily_rank,daily_movement,weekly_movement,country,snapshot_date,popularity,is_explicit,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,album_release_year
0,2HafqoJbgXdtjwCOvNEF14,Si No Estás,iñigo quintero,1,0,3,Global,2023-10-27,97,False,...,-8.720,1,0.0285,0.8270,0.000000,0.1380,0.524,98.224,4,2022
1,7x9aauaA9cu6tyfpHnqDLo,Seven (feat. Latto) (Explicit Ver.),"Jung Kook, Latto",2,4,0,Global,2023-10-27,97,True,...,-4.107,1,0.0434,0.3110,0.000000,0.0815,0.890,124.997,4,2023
2,3rUGC1vUpkDG9CZFHMur1t,greedy,Tate McRae,3,-1,2,Global,2023-10-27,99,True,...,-3.180,0,0.0319,0.2560,0.000000,0.1140,0.844,111.018,1,2023
3,4MjDJD8cW7iVeWInc2Bdyj,MONACO,Bad Bunny,4,-1,-3,Global,2023-10-27,96,True,...,-5.009,0,0.0680,0.1500,0.000402,0.5800,0.130,139.056,4,2023
4,7iQXYTyuG13aoeHxGG28Nh,PERRO NEGRO,"Bad Bunny, Feid",5,0,1,Global,2023-10-27,94,True,...,-2.248,1,0.2620,0.0887,0.000022,0.1790,0.345,96.057,4,2023

In [189]:
df_updated.count()

spotify_id            36400
name                  36400
artists               36400
daily_rank            36400
daily_movement        36400
weekly_movement       36400
country               36400
snapshot_date         36400
popularity            36400
is_explicit           36400
duration_ms           36400
album_name            36400
album_release_date    36400
danceability          36400
energy                36400
key                   36400
loudness              36400
mode                  36400
speechiness           36400
acousticness          36400
instrumentalness      36400
liveness              36400
valence               36400
tempo                 36400
time_signature        36400
album_release_year    36400
dtype: int64

In [190]:
# find the number of unique songs by spotify_id
df_updated["spotify_id"].nunique()

2203

In [191]:
df_updated.groupby("spotify_id").nunique()

,name,artists,daily_rank,daily_movement,weekly_movement,country,snapshot_date,popularity,is_explicit,duration_ms,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,album_release_year
spotify_id,,,,,,,,,,,,,,,,,,,,,
000n6Lx4yqUAslF1x3JeFY,1,1,5,5,7,1,10,2,1,1,...,1,1,1,1,1,1,1,1,1,1
003vvx7Niy0yvhvHt4a68B,1,1,17,11,18,4,10,1,1,1,...,1,1,1,1,1,1,1,1,1,1
006oGnrSZevqZTimsD2oh4,1,1,6,6,9,1,10,1,1,1,...,1,1,1,1,1,1,1,1,1,1
00E0Z2jrF7reoHps4zcbWQ,1,1,3,3,3,1,3,1,1,1,...,1,1,1,1,1,1,1,1,1,1
00TO3hVgOAgfKrRjrKEZxx,1,1,5,7,6,1,10,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7yS8LfvvFEhtGhKLk29j5a,1,1,4,4,4,1,6,4,1,1,...,1,1,1,1,1,1,1,1,1,1
7yfMu3Ez41fQXuD9gUbFjQ,1,1,4,4,5,1,7,1,1,1,...,1,1,1,1,1,1,1,1,1,1
7z260Mol7Xvxetkwx55dL4,1,1,11,9,12,2,10,5,1,1,...,1,1,1,1,1,1,1,1,1,1
7z8EC940EnKqsHQGz5NwEe,1,1,1,2,2,1,3,2,1,1,...,1,1,1,1,1,1,1,1,1,1
7zogy2wgR1sOBYLx9ouhcq,1,1,6,7,8,1,10,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [192]:
# group by spotify_id and name and find count of song listed in countries
df_updated.groupby(["spotify_id","name"])["country"].count()

spotify_id              name
000n6Lx4yqUAslF1x3JeFY  béke                 10
003vvx7Niy0yvhvHt4a68B  Mr. Brightside       34
006oGnrSZevqZTimsD2oh4  Diva Yorgun          10
00E0Z2jrF7reoHps4zcbWQ  Car Keys (Ayla)       3
00TO3hVgOAgfKrRjrKEZxx  7ALA                 10
                                             ..
7yS8LfvvFEhtGhKLk29j5a  2minuti               6
7yfMu3Ez41fQXuD9gUbFjQ  KOMMER DU IHÅG?       7
7z260Mol7Xvxetkwx55dL4  WHO (feat. P T K)    20
7z8EC940EnKqsHQGz5NwEe  Rockstar              3
7zogy2wgR1sOBYLx9ouhcq  UH LA LA LA          10
Name: country, Length: 2206, dtype: int64

In [193]:
# Get the distribution of data for the values of each column
df_updated.describe()

,daily_rank,daily_movement,weekly_movement,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,album_release_year
count,36400.000000,36400.000000,36400.000000,36400.000000,36400.000000,36400.000000,36400.000000,36400.000000,36400.000000,36400.000000,36400.000000,36400.000000,36400.000000,36400.000000,36400.000000,36400.000000,36400.000000,36400.000000
mean,25.451841,2.642637,15.022170,78.632005,194732.892802,0.690514,0.645493,5.535330,-6.637245,0.489093,0.110831,0.290448,0.018618,0.172441,0.529228,122.123556,3.913626,2021.880302
std,14.417992,9.538796,16.936231,15.059680,49597.066271,0.135352,0.161067,3.467505,2.653350,0.499888,0.100871,0.254943,0.095461,0.123211,0.225259,27.664620,0.429177,3.753832
min,1.000000,-38.000000,-36.000000,0.000000,0.000000,0.222000,0.024200,0.000000,-22.497000,0.000000,0.023200,0.000008,0.000000,0.015400,0.037300,47.914000,1.000000,1900.000000
25%,13.000000,-1.000000,0.000000,67.000000,162833.000000,0.598000,0.548000,2.000000,-8.043000,0.000000,0.042600,0.085600,0.000000,0.098500,0.363000,99.974000,4.000000,2023.000000
50%,25.000000,0.000000,10.000000,83.000000,188163.500000,0.706000,0.669000,6.000000,-6.210500,0.000000,0.066500,0.207000,0.000002,0.120000,0.524000,120.025000,4.000000,2023.000000
75%,38.000000,2.000000,29.000000,90.000000,220784.000000,0.800000,0.753000,8.000000,-4.915000,1.000000,0.146000,0.455000,0.000100,0.211000,0.710000,140.055000,4.000000,2023.000000
max,50.000000,49.000000,49.000000,100.000000,641941.000000,0.974000,0.997000,11.000000,1.155000,1.000000,0.784000,0.984000,0.968000,0.968000,0.978000,217.969000,5.000000,2023.000000

In [194]:
df_updated.head()

,spotify_id,name,artists,daily_rank,daily_movement,weekly_movement,country,snapshot_date,popularity,is_explicit,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,album_release_year
0,2HafqoJbgXdtjwCOvNEF14,Si No Estás,iñigo quintero,1,0,3,Global,2023-10-27,97,False,...,-8.720,1,0.0285,0.8270,0.000000,0.1380,0.524,98.224,4,2022
1,7x9aauaA9cu6tyfpHnqDLo,Seven (feat. Latto) (Explicit Ver.),"Jung Kook, Latto",2,4,0,Global,2023-10-27,97,True,...,-4.107,1,0.0434,0.3110,0.000000,0.0815,0.890,124.997,4,2023
2,3rUGC1vUpkDG9CZFHMur1t,greedy,Tate McRae,3,-1,2,Global,2023-10-27,99,True,...,-3.180,0,0.0319,0.2560,0.000000,0.1140,0.844,111.018,1,2023
3,4MjDJD8cW7iVeWInc2Bdyj,MONACO,Bad Bunny,4,-1,-3,Global,2023-10-27,96,True,...,-5.009,0,0.0680,0.1500,0.000402,0.5800,0.130,139.056,4,2023
4,7iQXYTyuG13aoeHxGG28Nh,PERRO NEGRO,"Bad Bunny, Feid",5,0,1,Global,2023-10-27,94,True,...,-2.248,1,0.2620,0.0887,0.000022,0.1790,0.345,96.057,4,2023

In [195]:
# split artist column from comma separated string to a list of artists
df_updated["artist_split"] = df_updated["artists"].str.split(",").tolist()
df_updated.head()

,spotify_id,name,artists,daily_rank,daily_movement,weekly_movement,country,snapshot_date,popularity,is_explicit,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,album_release_year,artist_split
0,2HafqoJbgXdtjwCOvNEF14,Si No Estás,iñigo quintero,1,0,3,Global,2023-10-27,97,False,...,1,0.0285,0.8270,0.000000,0.1380,0.524,98.224,4,2022,[iñigo quintero]
1,7x9aauaA9cu6tyfpHnqDLo,Seven (feat. Latto) (Explicit Ver.),"Jung Kook, Latto",2,4,0,Global,2023-10-27,97,True,...,1,0.0434,0.3110,0.000000,0.0815,0.890,124.997,4,2023,"[Jung Kook, Latto]"
2,3rUGC1vUpkDG9CZFHMur1t,greedy,Tate McRae,3,-1,2,Global,2023-10-27,99,True,...,0,0.0319,0.2560,0.000000,0.1140,0.844,111.018,1,2023,[Tate McRae]
3,4MjDJD8cW7iVeWInc2Bdyj,MONACO,Bad Bunny,4,-1,-3,Global,2023-10-27,96,True,...,0,0.0680,0.1500,0.000402,0.5800,0.130,139.056,4,2023,[Bad Bunny]
4,7iQXYTyuG13aoeHxGG28Nh,PERRO NEGRO,"Bad Bunny, Feid",5,0,1,Global,2023-10-27,94,True,...,1,0.2620,0.0887,0.000022,0.1790,0.345,96.057,4,2023,"[Bad Bunny, Feid]"

In [196]:
# Explode the dataset to get each artist on a new tuple for analysis and reset index
df_updated.explode("artist_split").reset_index()

,index,spotify_id,name,artists,daily_rank,daily_movement,weekly_movement,country,snapshot_date,popularity,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,album_release_year,artist_split
0,0,2HafqoJbgXdtjwCOvNEF14,Si No Estás,iñigo quintero,1,0,3,Global,2023-10-27,97,...,1,0.0285,0.827,0.000000,0.1380,0.524,98.224,4,2022,iñigo quintero
1,1,7x9aauaA9cu6tyfpHnqDLo,Seven (feat. Latto) (Explicit Ver.),"Jung Kook, Latto",2,4,0,Global,2023-10-27,97,...,1,0.0434,0.311,0.000000,0.0815,0.890,124.997,4,2023,Jung Kook
2,1,7x9aauaA9cu6tyfpHnqDLo,Seven (feat. Latto) (Explicit Ver.),"Jung Kook, Latto",2,4,0,Global,2023-10-27,97,...,1,0.0434,0.311,0.000000,0.0815,0.890,124.997,4,2023,Latto
3,2,3rUGC1vUpkDG9CZFHMur1t,greedy,Tate McRae,3,-1,2,Global,2023-10-27,99,...,0,0.0319,0.256,0.000000,0.1140,0.844,111.018,1,2023,Tate McRae
4,3,4MjDJD8cW7iVeWInc2Bdyj,MONACO,Bad Bunny,4,-1,-3,Global,2023-10-27,96,...,0,0.0680,0.150,0.000402,0.5800,0.130,139.056,4,2023,Bad Bunny
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57284,36397,26b3oVLrRUaaybJulow9kz,People,Libianca,48,2,0,AE,2023-10-18,88,...,0,0.0678,0.551,0.000013,0.1020,0.693,124.357,5,2022,Libianca
57285,36398,5ydjxBSUIDn26MFzU3asP4,Rainy Days,V,49,1,0,AE,2023-10-18,88,...,0,0.0875,0.739,0.000000,0.1480,0.282,74.828,4,2023,V
57286,36399,59NraMJsLaMCVtwXTSia8i,Prada,"cassö, RAYE, D-Block Europe",50,0,0,AE,2023-10-18,94,...,1,0.0375,0.001,0.000002,0.1130,0.422,141.904,4,2023,cassö
57287,36399,59NraMJsLaMCVtwXTSia8i,Prada,"cassö, RAYE, D-Block Europe",50,0,0,AE,2023-10-18,94,...,1,0.0375,0.001,0.000002,0.1130,0.422,141.904,4,2023,RAYE
57288,36399,59NraMJsLaMCVtwXTSia8i,Prada,"cassö, RAYE, D-Block Europe",50,0,0,AE,2023-10-18,94,...,1,0.0375,0.001,0.000002,0.1130,0.422,141.904,4,2023,D-Block Europe

In [204]:
spotify_dataset = df_updated.to_csv("/Users/meetapandit/spotify_visualization/spotify_dataset.csv")